### ISSUE TITLE
Download failed after TETR.IO 6.3.0 upgrade.

### ISSUE THREAD

**Issue by Kecxyz** [szymonszl/inoue#1]
After the 6.3.0 upgrade the `Accept` header is required to be `application/vnd.osk.theorypack`

![image](https://user-images.githubusercontent.com/41269576/180319366-8172d6fb-4ce8-49c7-8b12-bcd19519b24f.png)

![image](https://user-images.githubusercontent.com/41269576/180319544-12190bd0-1643-4ca3-ac61-fd8358ea8c09.png)

**Comment by szymonszl** [comment]
hmm, time to figure out msgpacking i guess? need to figure out if i can somehow force the API to send JSON, or bother osk for a proper game saving api again..

**Comment by szymonszl** [comment]
also hold on people actually use inoue??

**Comment by o5k** [comment]
> After the 6.3.0 upgrade the `Accept` header is required to be `application/vnd.osk.theorypack`

You can send `Accept: application/json` too. Just note that (esp. for replay downloading) this may be deprecated in the future to allow replays to be encoded more efficiently.

**Comment by szymonszl** [comment]
i was just implementing/testing that in fact, fixed in 2af22f37f3fd451172100c2cb2fda7cb1632aaa7
guess im calling that v0.2 also
